{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 89, in opens\n",
      "    with open('output.txt', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 10, in both\n",
      "    sample()\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 19, in sample\n",
      "    with open('comcast1.csv', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'comcast1.csv'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 10, in both\n",
      "    sample()\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 19, in sample\n",
      "    with open('comcast1.csv', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'comcast1.csv'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\users\\manan\\appdata\\local\\programs\\python\\python37-32\\lib\\tkinter\\__init__.py\", line 1705, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 10, in both\n",
      "    sample()\n",
      "  File \"<ipython-input-1-426dd13e3a5a>\", line 19, in sample\n",
      "    with open('comcast1.csv', 'r') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'comcast1.csv'\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import pandas as pd\n",
    "import csv\n",
    "import subprocess\n",
    "from tkinter import *\n",
    "import sys\n",
    "\n",
    "def both():\n",
    "\tsample()\n",
    "\twrite()\n",
    "#def printtext():\n",
    "def sample():\n",
    "\t\t\n",
    "\tglobal e\n",
    "\tsys.stdout = open(\"op.txt\",\"w\")\n",
    "\temail = e.get()\n",
    "\tx=Label(root, text=\"Enter the email\")\n",
    "\twith open('comcast1.csv', 'r') as f:\n",
    "\t    \n",
    "\t    wines = list(csv.reader(f))\n",
    "    \n",
    "\tframe = pd.DataFrame(wines)\n",
    "\tframe = frame[[0,1,2,]]\n",
    "\tframe.columns = ['Email','Name','Address']\n",
    "\n",
    "\t#print(frame)\n",
    "\n",
    "\t#print(\"enter email of the person\")\n",
    "\n",
    "\t#email = input()\n",
    "\n",
    "\t#rint(email)\n",
    "\t\n",
    "\tfor index,row in frame.iterrows():\n",
    "\t\tif row['Email']==email:\n",
    "\t\t\tprint(row)\n",
    "\t\t\tname=row[1]\n",
    "\t\t\t#email=row[2]\n",
    "\t\t\t#print(\"inside\",name)\n",
    "\t\telse:\n",
    "\t\t\tpass\n",
    "\t\tf.close()\n",
    "\twith open('new.csv', 'r') as f:\n",
    "\t    wines1 = list(csv.reader(f ,  delimiter=':'))\n",
    "\n",
    "\tdata = pd.DataFrame(wines1)\n",
    "\tdata = data[[0,1]]\n",
    "\tdata.columns = ['Email','Password']\n",
    "\n",
    "\n",
    "\tfor index,row in data.iterrows():\n",
    "\t\tif row['Email']==email:\n",
    "\t\t\tprint('Password'+\"--\"+row[1])\n",
    "\t\t\t#passw=row[1]\n",
    "\t\telse:\n",
    "\t\t\tpass\n",
    "\n",
    "\t\tf.close()\n",
    "\twith open('3.csv', 'r') as f:\n",
    "\t    wines2 = list(csv.reader(f ,  delimiter=':'))\n",
    "\n",
    "\tdata2 = pd.DataFrame(wines2)\n",
    "\tdata2 = data2[[0,1]]\n",
    "\tdata2.columns = ['Email','Phone']\n",
    "\n",
    "\n",
    "\tfor index,row in data2.iterrows():\n",
    "\t\tif row['Email']==email:\n",
    "\t\t\tprint('Phone'+\"--\"+row[1])\n",
    "\t\t\t#phone=row[1]\n",
    "\t\telse:\n",
    "\t\t\tpass\n",
    "\t\tf.close()\n",
    "\t\n",
    "\treturn\n",
    "\t\n",
    "def write():\n",
    "\twith open(\"output.txt\",\"w\") as f:\n",
    "\t\tif(f):\n",
    "\t\t\toutput=sample()\n",
    "\t\t\tf.write(str(output))\n",
    "\t\t\n",
    "\t\tf.close()\n",
    "\n",
    "\t\n",
    "def opens():\n",
    "\t\n",
    "\twith open('output.txt', 'r') as f:\n",
    "\t    \n",
    "\n",
    "\t\tif(f):\n",
    "\t\t\tif(textBox.get(\"1.0\",END))==\"\\n\":\n",
    "\t\t\t\t\n",
    "\t\t\t\t\tcontent=f.readlines()\n",
    "\t\t\t\t\tprint(str(content))\n",
    "\t\t\t\t\tfor line in content:\n",
    "\t\t\t\t\t\ttextBox.insert(END,line)\n",
    "\t\t\t\t\t\t\n",
    "\t\t\t\t\t\n",
    "\t\t\telse:\n",
    "\t\t\t\t\ttextBox.delete('1.0', END)\n",
    "\t\t\t\t\tcontent=f.readlines()\n",
    "\t\t\t\t\tprint(str(content))\n",
    "\t\t\t\t\tfor line in content:\n",
    "\t\t\t\t\t\ttextBox.insert(END,line)\n",
    "\t\t\t\n",
    "\t\t\treturn\t\t\t\n",
    "\t\t\t\n",
    "\t\t\n",
    "'''\n",
    "wines = list(csv.reader(f))\n",
    "\tv=StringVar()\n",
    "\tprint(wines[0])\n",
    "\tprint(v)\n",
    "\tw1 = Label(root, textvariable=wines[0])\n",
    "\tw1.pack()dteehan@comcast.net\n",
    "\tv.set(wines[0])\n",
    "'''\n",
    "\n",
    "\n",
    "root = Tk()\n",
    "#window=Tk()\n",
    "root.resizable(height=False,width=False)\n",
    "root.minsize(700,500)\n",
    "\n",
    "\n",
    "root.title('OSINT')\n",
    "display= Label(root, text=\"Enter Your Email\")\n",
    "e=Entry(root,width=20)\n",
    "e.pack()\n",
    "e.focus_set()\n",
    "\n",
    "\n",
    "b = Button(root,text='okay',command=both)\n",
    "c= Button(root,text=\"Show details of the breach\",command=opens)\n",
    "textBox=Text()\n",
    "textBox.place(x=30,y=80,height=200)\n",
    "display.pack()\n",
    "c.pack()\t\n",
    "\n",
    "b.pack(side='bottom')\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
